### PR TITLE
Be/feature/action

### PR DESCRIPTION
**Pull request by bgmrsln**
* Implemented the following apis:
   - get group(need,resource tuples) info by action id: it checks whether need-resource matches have the same type, and returns recurrence, date details for user to be print on UI: [details](https://github.com/bounswe/bounswe2023group2/pull/577#issuecomment-1826763288)
   - create action with [action model](https://github.com/bounswe/bounswe2023group2/pull/577#issuecomment-1826764039) (You can also find fields on the form_fields endpoint)

   - Get all actions
   - get action by action id
   - action done for updating resource and need status
   - cancel action
   
* Also added recurrency to need and resource ednpoints
* Added ActionHistory field to resource, and action_used field to need for cancelling an action
* added get form_fields/action endpoint

### CODE REVIEW

**Comment by bgmrsln** [comment]
Group info api can be used as:
image

**Comment by bgmrsln** [comment]
Action Model:
image

**Review by mehmetkuzu — CHANGES_REQUESTED** [review]
Can you check the part where you decrease the resource quantities. Seems like one of the needs is ignored for multiple need actions

**Comment by bgmrsln** [comment]
> Can you check the part where you decrease the resource quantities. Seems like one of the needs is ignored for multiple need actions
Just fixed it, thanks for noticing

**Comment by mehmetkuzu** [comment]
> > Can you check the part where you decrease the resource quantities. Seems like one of the needs is ignored for multiple need actions
> > Just fixed it, thanks for noticing

Great. Thanks.

**Review by mehmetkuzu — APPROVED** [review]

**Pull request merged**
