### PR TITLE
Be/feature/resource

### PR DESCRIPTION
**Pull request by rburaksaritas**
I implemented the model and CRUD endpoinds for resource objects.

- Models/resource_model.py
- Services/resource_service.py
- Controllers/resource_controller.py

### CODE REVIEW

**Review by mehmetkuzu — COMMENTED** [review]
By convention we are using the api routes like:
/api/routers/...
so in main.py
app.include_router(resource_controller.router, prefix = "/resource", tags=["resource"])
should become 
app.include_router(resource_controller.router, prefix = "/api/resource", tags=["resource"])

**Review by mehmetkuzu — COMMENTED** [review]
For resource update:
The API should be able to answer partial update calls like
{
  "created_by": "başkası"
}

this returns error:
{
  "detail": [
    {
      "loc": [
        "body",
        "condition"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "initialQuantity"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "unsuppliedQuantity"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "type"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "details"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}

**Comment by bgmrsln** [comment]
Maybe we can add enum for resource types later after discussing with rest of the team.

**Comment by bgmrsln** [comment]
Can you delete .idea folder and add it to .gitignore please? I guess it is not necessary @mehmetkuzu @rburaksaritas

**Comment by rburaksaritas** [comment]
Following updates are made on the PR:

- Added api/ prefix to the resource router.
- Updated resource update feature to allow optional fields.
- Ignored backend/.idea/ folder.

**Review by bgmrsln — APPROVED** [review]
I think it is good now. Thanks for your effort

**Pull request merged**
