### PR TITLE
De/feature/add docker compose

### PR DESCRIPTION
**Pull request by mervegrbz**
## Changelog:
- Add docker-compose
- add dockerfiles for backend and frontend

### CODE REVIEW

**Comment by mervegrbz** [comment]
@bgmrsln Can you check the dockerfile in backend? I just copied it from previous semester 👀

**Comment by mervegrbz** [comment]
> why we use npm instead of yarn?

at first step, I thought I could be good to use simple one since many of us started to learn :)

**Comment by bgmrsln** [comment]
Looks good to me! <3

**Review by bgmrsln — APPROVED** [review]
Looks good to me <3

**Pull request merged**
