### PR TITLE
Be/feature/auth related start

### PR DESCRIPTION
**Pull request by mehmetkuzu**
Authentication (login) and authorization scheme (authorized calls to API's using session tokens and usernames) a first version is prepared.

### CODE REVIEW

**Comment by bgmrsln** [comment]
Can you explain why api calls have response in their body

**Comment by bgmrsln** [comment]
And why authentication is required with creating user? @mehmetkuzu

**Comment by mehmetkuzu** [comment]
> Can you explain why api calls have response in their body

Sure:
response is actually passed by fastapi automatically. That is, the API caller does not set it. It is not one of the API parameters.

We put the response parameter in our API function so that we can set the response_code.

**Comment by mehmetkuzu** [comment]
> And why authentication is required with creating user? @mehmetkuzu
It was a temporary decision for dev process. I added two lines to the comments
#Temporary code
    # So that the programmers may create users while testing.
    # Will be commented out later

**Comment by mehmetkuzu** [comment]
Burak updated his branch already. So resource branch will be PR'd.

**Pull request closed without merging**
