### PR TITLE
Be/feature/user profile improvements

### PR DESCRIPTION
**Pull request by mehmetkuzu**
On this branch:
* Some minor changes on resource code which were revealed in BE team meeting.
* User profile is being improved. Optional info for users added.
* Language skills (as a profile info is added)
I preferred to open a pull request at this stage before finalizing other profile elements (skills, professions, social media links). For:
* UI side is probably waiting for API infrastructure to speed up their work.
* Before going further BE code might need some corrections.

### CODE REVIEW

**Comment by mehmetkuzu** [comment]
For reviewers:
- Don't forget to manually put Config.py (with secrets)
- The mongo database might be empty again. Begin with signup derim.

Attached is my latest Postman collection.
[RESTful API basics- CRUD, test & variable.postman_collection.json](https://github.com/bounswe/bounswe2023group2/files/13195010/RESTful.API.basics-.CRUD.test.variable.postman_collection.json)

**Comment by bgmrsln** [comment]
Why it returns error when user optional info does not exists: 
image
- do we require an initial null user optional info in the database?

**Comment by mehmetkuzu** [comment]
> Why it returns error when user optional info does not exists: 
> image
> - do we require an initial null user optional info in the database?

You are right. We can return an empty array.

**Comment by mehmetkuzu** [comment]
> > Why it returns error when user optional info does not exists: 
> > image
> > - do we require an initial null user optional info in the database?
> 
> You are right. We can return an empty array. 

But not a null initial info I think

**Comment by mehmetkuzu** [comment]
Now returns empty array if no record found.

**Review by bgmrsln — APPROVED** [review]
Endpoints are working, LGTM!

**Pull request merged**
