### PR TITLE
Mo/feature/upload-document

### LINKED ISSUE #777: Mobile - Upload Document
### Issue Description

A user should be able to upload document to prove his/her proficiency

### Deadline of the Issue

26.12.2023

### Reviewer

Egecan Serbester

### PR DESCRIPTION
**Pull request by cahidenes**
Upload document feature is implemented. A user can upload a document to prove his skill. There is an attachment icon in the skill part of the user profile. A user can attach a file.

image

This PR resolves #777

### CODE REVIEW

**Comment by egecans** [comment]
I had a UI issue when I started the program, after I uploaded a document it still continues 
Screenshot 2023-12-25 at 05 14 45
I also can't reach that image but I can see it successfully. This may originate because of my device (because it's an Android POS device :D)
Screenshot 2023-12-25 at 05 16 11

**Comment by cahidenes** [comment]
The UI error is because I am setting hint instead of text. Setting text has a disadvantage of making the spinner only one choice (if the user wants to select other choices, he/she need to delete the text first). I chose hint before, now I changed this to text.
Also I could not reproduce the second error. I can see the downloaded images on my physical android device.

**Comment by egecans** [comment]
Ok, now I can see that image and that error is fixed. However there are still some errors in Edit Profile, one of which is keeping profile visibility, it couldn't change although I changed it. Can you quickly fix it ?

**Review by egecans — APPROVED** [review]
It works, seems fine thanks for your effort!

**Pull request merged**
