### PR TITLE
MO/feature/edit forms backend

### PR DESCRIPTION
**Pull request by egecans**
Closing #497

### CODE REVIEW

**Comment by higurbuzz** [comment]
Resource editing works, but when I try to edit twice in a row, the application crashes after performing the edit.
The error code is as follows:
```
java.lang.IllegalStateException: Fragment AddResourceFragment not associated with a fragment manager.
at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)
at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.invoke$lambda$0(AddResourceFragment.kt:150)
at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.$r8$lambda$ue9lg8n33Fst1y7wGkgsbd6_bxY(Unknown Source:0)
at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
```

**Comment by egecans** [comment]
> Resource editing works, but when I try to edit twice in a row, the application crashes after performing the edit. The error code is as follows:
> 
> ```
> java.lang.IllegalStateException: Fragment AddResourceFragment not associated with a fragment manager.
> at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)
> at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.invoke$lambda$0(AddResourceFragment.kt:150)
> at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.$r8$lambda$ue9lg8n33Fst1y7wGkgsbd6_bxY(Unknown Source:0)
> at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
> ```

A very detailed test, thank you. Since even the experienced test team in the company I worked for could not test like this, we received multi-click errors from the field months after the feature was released.

**Comment by egecans** [comment]
> > Resource editing works, but when I try to edit twice in a row, the application crashes after performing the edit. The error code is as follows:
> > ```
> > java.lang.IllegalStateException: Fragment AddResourceFragment not associated with a fragment manager.
> > at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)
> > at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.invoke$lambda$0(AddResourceFragment.kt:150)
> > at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.$r8$lambda$ue9lg8n33Fst1y7wGkgsbd6_bxY(Unknown Source:0)
> > at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
> > ```
> 
> A very detailed test, thank you. Since even the experienced test team in the company I worked for could not test like this, we received multi-click errors from the field months after the feature was released.

This was the issue in our all submit buttons, I tried to change most of them but if I missed or the next UI implementation, please consider this fast multi-clicking issue. You can follow my guide in this [commit](https://github.com/bounswe/bounswe2023group2/pull/511/commits/9e8724e031ebc57267d08b4cb01cc77b59a7ba7e)

**Comment by egecans** [comment]
> Resource editing works, but when I try to edit twice in a row, the application crashes after performing the edit. The error code is as follows:
> 
> ```
> java.lang.IllegalStateException: Fragment AddResourceFragment not associated with a fragment manager.
> at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)
> at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.invoke$lambda$0(AddResourceFragment.kt:150)
> at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1.$r8$lambda$ue9lg8n33Fst1y7wGkgsbd6_bxY(Unknown Source:0)
> at com.example.disasterresponseplatform.ui.activity.resource.AddResourceFragment$submitResource$1$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
> ```

Now, I figured out the bug you mentioned, when entering the fragment then going back and entering the same fragment, it couldn't having been attached the fragment with parentFragmentManager. I searched why it happened, and figuring it out with checking Fragment.isAdded method. When I checked it with this, this bug never came again. Thanks for your detailed test again

**Comment by higurbuzz** [comment]
Now all is done. Great job, thank you. I tested and it is working. I also merged AddNeed and EditNeed pages in this PR.

**Review by higurbuzz — APPROVED** [review]

**Pull request merged**
