### PR TITLE
Mo/feature/profile-picture

### LINKED ISSUE #732: Mobile - Profile Picture
### Issue Description

Upload, get and show profile picture should be implemented

### Deadline of the Issue

19.12.2023

### Reviewer

Egecan Serbester

### PR DESCRIPTION
**Pull request by cahidenes**
Implement upload profile picture in Edit Profile Fragment. Profile picture also appears in Profile Fragment.

This PR resolves #732

### CODE REVIEW

**Comment by egecans** [comment]
It works fine but when I upload a profile picture and then trying to update it, it gives me an error

**Comment by cahidenes** [comment]
Does it give an error or just won't update the profile photo?

**Comment by cahidenes** [comment]
A small bug in the backend was causing the profile photo not to update when there is no other information in the profile. This was fixed in this [PR](https://github.com/bounswe/bounswe2023group2/pull/857). Now it should work fine.

**Comment by egecans** [comment]
The problem continues, it may happen because of both language, proficiency and profile picture selection. You can test with choosing all of them while editing the profile.

**Comment by egecans** [comment]
Now It works perfect, well done!

**Review by egecans — APPROVED** [review]
Good job,

**Pull request merged**
