### PR TITLE
Mo/feature/save added activities

### PR DESCRIPTION
**Pull request by egecans**
In this PR, when the user clicks the add activity (need, resource, event) button if there is no internet connection, no Internet Connection Activity Form is opened. After opening that form, users can fill in the required fields and save them into a local database. If it is saved successfully, users will be informed with a Toast message "It is saved in Local, It will be uploaded when you connect to the internet"

When users have an internet connection: 
 it checks whether some objects in the local database are created without a connection
 If some objects are created locally, then it will post these objects to the backend and delete them from a local database.
 If it posts some objects into the backend successfully it shows a toast "Your Local Objects are Posted into Backend Successfully"
 Then when user refresh the page they can see their local objects from the list that is fetched from the backend.

Emergency will be added after backend implementation is done

### CODE REVIEW

**Review by cahidenes — COMMENTED** [review]
Great Job! Massive improvement. A few notes:
- Address always translates to 0 0. This could be chosen from map and sent as coordinates.
- When app opened with connection, local database is pushed correctly. But when another fragment is opened and closed, the toast message appears again.

**Comment by egecans** [comment]
> Great Job! Massive improvement. A few notes:
> 
> * Address always translates to 0 0. This could be chosen from map and sent as coordinates.
> * When app opened with connection, local database is pushed correctly. But when another fragment is opened and closed, the toast message appears again.

I'm trying to select coordinates from the map if it works without connection (I thought it didn't work), but the second issue couldn't happen to me, maybe you didn't update that branch after my solving for this bug was pushed. Can you try with the latest version of that branch?

**Comment by egecans** [comment]
with the commit [b0a4af5](https://github.com/bounswe/bounswe2023group2/pull/841/commits/b0a4af5aa96ff7be4766b5a0b73ca48052b75bff)
now users can either select the location from the map or enter their addresses under the location edit text.
If they select the location from a map, their x and y addresses are stored and then sent to the backend,
If they write their addresses then their input is saved and sent to the backend under the details part and their x, and y will be 0.0 0.0 to understand they give their addresses by hand instead of selecting a location from the map.
I also carry the map icon to the left to prevent errors when location is not chosen ( ! mark had covered the map, this is fixed by this)

**Review by cahidenes — APPROVED** [review]
Both points that I mentioned are resolved. Great Job!

**Pull request merged**
